apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-dependency
spec:
  destination:
    namespace: miles-scratch
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
      version: v2
    path: helm-dependency
    repoURL: https://github.com/milesbxf/argocd-demo.git
    targetRevision: HEAD
